title: V Embedded
description: Embedded systems education and products
baseurl: ""
url: "https://v-embedded.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  products:
    output: true
    permalink: /products/:name/
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      permalink: /tutorials/:title/

exclude:
  - node_modules
  - vendor
  - site
  - .github
  - scripts

permalink: /:categories/:title/
