# Site Settings
title: V Embedded LLC
description: Embedded hardware and software developer.
url: "https://www.vembedded.com"
baseurl: "/"
author: "EV"
email: "info@vembedded.com"

year: 2025
company: "V Embedded LLC"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

seo:
  title: "V Embedded LLC"
  description: "Custom embedded systems design, firmware development, and hardware prototyping for connected devices and IoT solutions."
  url: "https://www.vembedded.com"
  image: "https://www.vembedded.com/assets/images/logo.svg"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

sass:
  load_paths:
    - node_modules
  style: compressed

collections:
  products:
    output: true
